"""course lifecycle status

Revision ID: 0ab8957dcb39
Revises: 0deb80fcebd5
Create Date: 2026-09-17 07:50:22.743242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab8957dcb39'
down_revision: Union[str, Sequence[str], None] = '0deb80fcebd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('status', sa.String(length=32), nullable=False, server_default='published',))
    op.create_index(op.f('ix_courses_status'), 'courses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_status'), table_name='courses')
    op.drop_column('courses', 'status')
    # ### end Alembic commands ###
