"""add comments model

Revision ID: 1c0d36ca6c32
Revises: 969d8f357bfd
Create Date: 2026-09-24 17:26:47.331781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0d36ca6c32'
down_revision: Union[str, Sequence[str], None] = '969d8f357bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=True),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('code_task_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('\n            (\n                CASE WHEN lecture_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN question_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN task_id IS NOT NULL THEN 1 ELSE 0 END +\n                CASE WHEN code_task_id IS NOT NULL THEN 1 ELSE 0 END\n            ) = 1\n            ', name='ck_comments_exactly_one_target'),
    sa.ForeignKeyConstraint(['code_task_id'], ['code_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_code_task_created_at', 'comments', ['code_task_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_comments_lecture_created_at', 'comments', ['lecture_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_comments_question_created_at', 'comments', ['question_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_comments_task_created_at', 'comments', ['task_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_task_created_at', table_name='comments')
    op.drop_index('ix_comments_question_created_at', table_name='comments')
    op.drop_index('ix_comments_lecture_created_at', table_name='comments')
    op.drop_index('ix_comments_code_task_created_at', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
