"""add course catalog metadata

Revision ID: ead00a4b3a8e
Revises: 0ab8957dcb39
Create Date: 2026-09-18 05:27:16.073306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead00a4b3a8e'
down_revision: Union[str, Sequence[str], None] = '0ab8957dcb39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('short_description', sa.String(length=280), nullable=False, server_default=''))
    op.add_column('courses', sa.Column('difficulty', sa.String(length=32), nullable=False, server_default='beginner'))
    op.add_column('courses', sa.Column('tag_names', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'tag_names')
    op.drop_column('courses', 'difficulty')
    op.drop_column('courses', 'short_description')
    op.drop_column('courses', 'cover_image_url')
    # ### end Alembic commands ###
